language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r backend/requirements.txt
  - pip install flake8
  - pip install pytest
script:
  - flake8 --max-line-length=150 backend/api/
  - pytest backend/api/application/tests.py 
